language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true

install:
  - mkdir -p /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - phpenv config-add test/phpconfig.ini
  - travis_retry composer install --no-interaction --prefer-dist